---

### Keystone Settings ###
#keystone_server_ip: "{{ controller1_mgmt_ip }}"
cloud: openstack_newton # name of cloud defined in cloud.yaml
default_domain: default
keystone_auth_admin_token: insecuretoken123
keystone_revoke_driver: keystone.contrib.revoke.backends.sql.Revoke
keystone_token_provider: fernet
keystone_admin_password: openstack
# keystone_token_driver: keystone.token.persistence.backends.memcache.Token

# Endpoint Settings #
public_endpont_ip: 10.0.0.11
admin_endpoint_ip: 10.0.0.11
internal_endpoint_ip: 10.0.0.11

keystone_service_adminurl: http://{{ admin_endpoint_ip }}:35357
keystone_service_publicurl: http://{{ public_endpont_ip }}:5000
keystone_service_internalurl: http://{{ internal_endpoint_ip }}:5000
keystone_service_adminuri_insecure: true
keystone_service_region: RegionOne

nova_service_adminurl: http://{{ admin_endpoint_ip }}:8774/v2.1/%(tenant_id)s
nova_service_publicurl: http://{{ public_endpont_ip }}:8774/v2.1/%(tenant_id)s
nova_service_internalurl: http://{{ internal_endpoint_ip }}:8774/v2.1/%(tenant_id)s

network_service_adminurl: http://{{ admin_endpoint_ip }}:9696
network_service_publicurl: http://{{ public_endpont_ip }}:9696
network_service_internalurl: http://{{ internal_endpoint_ip }}:9696

# Projects & Accounts #
admin_project: admin
admin_username: admin
admin_password: openstack
admin_email: admin@{{domain_name}}
admin_domain: default

demo_project: demo
demo_username: demo
demo_password: openstack
demo_email: demo@{{domain_name}}
demo_domain: default
demo_role: user

keystone_project: service
keystone_username: keystone
keystone_password: openstack
keystone_email: keystone@{{domain_name}}
keystone_domain: default

glance_project: service
glance_username: glance
glance_password: openstack
glance_email: glance@{{domain_name}}
glance_domain: default
glance_role: admin

nova_project: service
nova_username: nova
nova_password: openstack
nova_email: nova@{{domain_name}}
nova_domain: default
nova_role: admin

neutron_project: service
neutron_username: neutron
neutron_password: openstack
neutron_email: neutron@{{domain_name}}
neutron_domain: default
