---

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  when: ansible_os_family == "Debian"
  tags: 
    - packages
    - ubuntu

- name: Install  Packages
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - ubuntu-cloud-keyring
  when: ansible_os_family == "Debian"
  tags:
    - packages
    - ubuntu

# - name: Install software-properties-common
#   apt: name=software-properties-common state=present
#   when: ansible_os_family == "Debian"
#   tags: 
#     - packages
#     - ubuntu
  
# - name: Install ubuntu-cloud-keyring
#   apt: name=ubuntu-cloud-keyring state=present
#   when: ansible_os_family == "Debian"
#   tags:
#     - packages
#     - ubuntu

- name: Add Ubuntu Cloud Archive Repository
  apt_repository: repo='{{ cloud_archive_repository }}' state=present
  when: ansible_os_family == "Debian"
  tags:
    - cloud_archive_repository
    - ubuntu
      
- name: Update Cache again
  apt: update_cache=yes
  when: ansible_os_family == "Debian"
  tags:
    - cloud_archive_repository
    - ubuntu

- name: Add CentOS OpenStack Repo
  yum: 
    name: "{{ centos_openstack_release }}"
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - redhat

- name: Upgrade CentOS
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
    - upgrade
    - upgrade_centos
    - centos

- name: Upgrade Ubuntu
  apt: upgrade=dist
  when: ansible_os_family == "Debian"
  tags:
    - upgrade
    - upgrade_ubuntu
    - ubuntu

- name: Is Reboot Required
  stat: 
    path: /var/run/reboot-required.pkgs
  register: stat_result
  tags:
    - upgrade
    - common

- name: Test stat results
  debug:
    var: stat_result
    verbosity: 3
  tags:
    - upgrade
    - common

- name: Reboot Controller?
  debug:
    msg: "Controller Reboot required"
  when: (inventory_hostname | search("controller")) and (stat_result.stat.exists == True) 
  notify: vagrant-shutdown
  tags:
    - upgrade
    - common

- name: Reboot Compute?
  debug:
    msg: "Compute Reboot required"
  when: (inventory_hostname | search("compute")) and (stat_result.stat.exists == True) 
  notify: restart
  tags:
    - upgrade
    - common

- name: Reboot Block?
  debug:
    msg: "Block Reboot required"
  when: (inventory_hostname | search("block")) and (stat_result.stat.exists == True) 
  notify: restart
  tags:
    - upgrade
    - common

- name: Reboot Object?
  debug:
    msg: "Object Reboot required"
  when: (inventory_hostname | search("object")) and (stat_result.stat.exists == True) 
  notify: restart
  tags:
    - upgrade
    - common

- name: vagrant-shutdown controller
  become: false
  local_action: command vagrant halt {{ ansible_hostname }}
  when: (inventory_hostname | search("controller")) and (stat_result.stat.exists == True) 
  tags:
    - upgrade
    - common

- name: vagrant boot controller
  become: false
  local_action: command vagrant up {{ ansible_hostname }}
  when: (inventory_hostname | search("controller")) and (stat_result.stat.exists == True) 
  tags:
    - upgrade
    - common

- name: Restart Compute
  shell: sleep 2 && shutdown -r now "Ansible triggered restart"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: (inventory_hostname | search("compute")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Wait for Compute Nodes to reboot
  local_action: wait_for host={{ ansible_hostname }} state=started delay=20 timeout=30
  become: false
  when: (inventory_hostname | search("compute")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Restart Block
  shell: sleep 2 && shutdown -r now "Ansible triggered restart"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: (inventory_hostname | search("block")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Wait for Block Nodes to reboot
  local_action: wait_for host={{ ansible_hostname }} state=started delay=20 timeout=30
  become: false
  when: (inventory_hostname | search("block")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Restart Object
  shell: sleep 2 && shutdown -r now "Ansible triggered restart"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: (inventory_hostname | search("object")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Wait for Object Nodes to reboot
  local_action: wait_for host={{ ansible_hostname }} state=started delay=20 timeout=30
  become: false
  when: (inventory_hostname | search("object")) and (stat_result.stat.exists == True)
  tags:
    - upgrade
    - common

- name: Install python-openstackclient
  package:
    name: python-openstackclient
    state: present
  tags:
    - packages
    - common

- name: Install openstack-selinux
  package:
    name: openstack-selinux
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - redhat