---
  
- name: restart all ubuntu
  service: 
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  when: ansible_os_family == "Debian"
  tags:
    - ubuntu

- name: restart all redhat
  systemd: 
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-api
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  when: ansible_os_family == "RedHat"
  tags:
    - redhat